import "./globals.css";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/Providers";
// import { Inter } from "next/font/google";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import AppBar from "@/components/AppBar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Psikotes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Toaster />
          {/* <Header /> */}
          <AppBar />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
