import "./globals.css";
import { Toaster } from "react-hot-toast";
// import { Inter } from "next/font/google";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Psikotes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <Toaster />
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
